"""
Unit tests for the Alembic migration setup (Task 2.3).

These tests exercise the real migration path — alembic upgrade head —
against a temporary SQLite file, then inspect the resulting schema.
They are intentionally slower than pure-unit tests (they run migrations)
but validate that the generated SQL actually matches the ORM models.
"""

import sqlite3
from pathlib import Path

import pytest
from alembic.command import downgrade, upgrade
from alembic.config import Config

EXPECTED_TABLES = {
    "users",
    "refresh_tokens",
    "machines",
    "user_machines",
    "scripts",
    "script_target_state",
    "jobs",
    "audit_log",
    "alembic_version",
}


@pytest.fixture
def alembic_cfg(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Config:
    db_file = tmp_path / "test.sqlite"
    monkeypatch.setenv("CSL_DATABASE_URL", f"sqlite+aiosqlite:///{db_file}")
    cfg = Config("alembic.ini")
    return cfg


def _table_names(db_file: Path) -> set[str]:
    conn = sqlite3.connect(db_file)
    tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    conn.close()
    return tables


def _column_names(db_file: Path, table: str) -> set[str]:
    conn = sqlite3.connect(db_file)
    cols = {row[1] for row in conn.execute(f"PRAGMA table_info({table})")}  # noqa: S608
    conn.close()
    return cols


# ---------------------------------------------------------------------------
# upgrade head
# ---------------------------------------------------------------------------


def test_upgrade_head_creates_all_tables(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    tables = _table_names(tmp_path / "test.sqlite")
    assert EXPECTED_TABLES.issubset(tables)


def test_upgrade_head_is_idempotent(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    upgrade(alembic_cfg, "head")  # must not raise
    tables = _table_names(tmp_path / "test.sqlite")
    assert EXPECTED_TABLES.issubset(tables)


# ---------------------------------------------------------------------------
# Column spot-checks (verify migration matches ORM definitions)
# ---------------------------------------------------------------------------


def test_users_columns(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    cols = _column_names(tmp_path / "test.sqlite", "users")
    assert cols == {"id", "username", "password_hash", "role", "created_at", "disabled"}


def test_machines_columns(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    cols = _column_names(tmp_path / "test.sqlite", "machines")
    assert cols == {
        "id",
        "name",
        "ssh_host",
        "ssh_port",
        "ssh_user",
        "ssh_key_encrypted",
        "key_fingerprint",
        "agent_port",
        "scripts_dir",
        "platform",
        "mac_address",
        "created_at",
    }


def test_jobs_columns(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    cols = _column_names(tmp_path / "test.sqlite", "jobs")
    assert cols == {
        "id",
        "job_uuid",
        "machine_id",
        "script_id",
        "built_in_action",
        "user_id",
        "params_json",
        "status",
        "persistent",
        "started_at",
        "ended_at",
        "exit_code",
        "log_path",
    }


def test_script_target_state_columns(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    cols = _column_names(tmp_path / "test.sqlite", "script_target_state")
    assert cols == {
        "machine_id",
        "script_id",
        "state",
        "approved_md5",
        "pending_md5",
        "last_refreshed_at",
    }


# ---------------------------------------------------------------------------
# downgrade base
# ---------------------------------------------------------------------------


def test_downgrade_base_removes_all_tables(alembic_cfg: Config, tmp_path: Path) -> None:
    upgrade(alembic_cfg, "head")
    downgrade(alembic_cfg, "base")
    tables = _table_names(tmp_path / "test.sqlite")
    assert tables == {"alembic_version"} or not tables  # version table may persist


# ---------------------------------------------------------------------------
# ORM round-trip against a migrated schema
#
# This is the test neither test_models.py nor the pure migration tests catch:
# it proves the migrated schema is actually compatible with the SQLAlchemy ORM
# models. test_models.py uses create_all() (bypasses Alembic), so if the
# autogenerated migration drifted from the models this test would fail while
# test_models.py would not.
# ---------------------------------------------------------------------------


def test_orm_round_trip_on_migrated_db(alembic_cfg: Config, tmp_path: Path) -> None:
    import asyncio

    from sqlalchemy import select
    from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

    from control_station_lite.server.db.models import User

    db_url = f"sqlite+aiosqlite:///{tmp_path / 'test.sqlite'}"

    # Migration runs first (sync, uses its own asyncio.run internally).
    upgrade(alembic_cfg, "head")

    # ORM operations run in a fresh event loop — cannot nest inside pytest-asyncio.
    async def _run() -> None:
        engine = create_async_engine(db_url)
        factory = async_sessionmaker(engine, expire_on_commit=False)

        async with factory() as session:
            session.add(User(username="integration_user", password_hash="h", role="admin"))
            await session.commit()

        async with factory() as session:
            result = await session.execute(select(User).where(User.username == "integration_user"))
            user = result.scalar_one()
            assert user.role == "admin"
            assert user.disabled is False

        await engine.dispose()

    asyncio.run(_run())
